look into spicy similarity vectors !

In [36]:
import numpy as np
from sklearn.datasets import load_digits

In [37]:
data, labels = load_digits(return_X_y=True)
(n_samples, n_features), n_digits = data.shape, np.unique(labels).size

print(f"# digits: {n_digits}; # samples: {n_samples}; # features {n_features}")

# digits: 10; # samples: 1797; # features 64


In [22]:
data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [21]:
labels

array([0, 1, 2, ..., 8, 9, 8])

In [9]:
n_digits

10

In [10]:
n_samples

1797

In [11]:
n_features

64

In [23]:
import numpy as np
import matplotlib.pyplot as plt

# Though the following import is not directly being used, it is required
# for 3D projection to work with matplotlib < 3.2
import mpl_toolkits.mplot3d  # noqa: F401

from sklearn.cluster import KMeans
from sklearn import datasets

np.random.seed(5)

iris = datasets.load_iris()
X = iris.data
y = iris.target

In [24]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [25]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('steam_game_data.csv')

In [3]:
df.head()

Unnamed: 0                             title  \
0           0  Counter-Strike: Global Offensive   
1           1                     Apex Legends™   
2           2                             Stray   
3           3                Grand Theft Auto V   
4           4                       MultiVersus   

                                           hyperlink  \
0  https://store.steampowered.com/app/730/Counter...   
1  https://store.steampowered.com/app/1172470/Ape...   
2  https://store.steampowered.com/app/1332010/Str...   
3  https://store.steampowered.com/app/271590/Gran...   
4  https://store.steampowered.com/app/1818750/Mul...   

                                             is game  \
0  All Games > Free to Play Games > Counter-Strik...   
1  All Games > Action Games > Apex Legends Offici...   
2  All Games > Adventure Games > Annapurna Intera...   
3      All Games > Action Games > Grand Theft Auto V   
4       All Games > Free to Play Games > MultiVersus   

                                            Genres main_genre     sub_genre  \
0                ['Action,', 'Free', 'to', 'Play']     Action  Free to play   
1  ['Action,', 'Adventure,', 'Free', 'to', 'Play']     Action     Adventure   
2                          ['Adventure,', 'Indie']  Adventure         Indie   
3                         ['Action,', 'Adventure']     Action     Adventure   
4                ['Action,', 'Free', 'to', 'Play']     Action  Free to play   

   price_in_rand  discount_price  discount_percent  ...  \
0            0.0             0.0                 0  ...   
1            0.0             0.0                 0  ...   
2          195.0           195.0                 0  ...   
3            0.0             0.0                 0  ...   
4            0.0             0.0                 0  ...   

                                                tags              developer  \
0  ['FPS', 'Shooter', 'Multiplayer', 'Competitive...                  Valve   
1  ['Free to Play', 'Multiplayer', 'Battle Royale...  Respawn Entertainment   
2  ['Cats', 'Adventure', 'Cyberpunk', 'Cute', 'At...      BlueTwelve Studio   
3  ['Open World', 'Action', 'Multiplayer', 'Autom...         Rockstar North   
4  ['Multiplayer', 'Co-op', '2D Fighter', 'Action...     Player First Games   

               publisher                                   game description  \
0                  Valve  About This Game Counter-Strike: Global Offensi...   
1        Electronic Arts  About This Game Conquer with character in Apex...   
2  Annapurna Interactive  About This Game Lost, alone and separated from...   
3         Rockstar Games  About This Game When a young street hustler, a...   
4     Warner Bros. Games  About This Game CharactersChoose from Harley Q...   

  release_year release_month  release_day percent_of_reviews_positive  \
0         2012           Aug           21                          88   
1         2020           Nov            4                          86   
2         2022           Jul           19                          97   
3         2015           Apr           13                          85   
4         2022           Jul           19                          89   

   number_of_reviews  category  
0            6545979     Games  
1             486153     Games  
2              56406     Games  
3            1251157     Games  
4              42353     Games  

[5 rows x 22 columns]

In [8]:
df = df[['title', 'tags']]
df.head()

title  \
0  Counter-Strike: Global Offensive   
1                     Apex Legends™   
2                             Stray   
3                Grand Theft Auto V   
4                       MultiVersus   

                                                tags  
0  ['FPS', 'Shooter', 'Multiplayer', 'Competitive...  
1  ['Free to Play', 'Multiplayer', 'Battle Royale...  
2  ['Cats', 'Adventure', 'Cyberpunk', 'Cute', 'At...  
3  ['Open World', 'Action', 'Multiplayer', 'Autom...  
4  ['Multiplayer', 'Co-op', '2D Fighter', 'Action...

In [17]:
def clean(string):
    return string.replace('[','').replace(']','').replace("'",'')

In [20]:
df['tags'] = df['tags'].apply(clean)

In [22]:
df

title  \
0                       Counter-Strike: Global Offensive   
1                                          Apex Legends™   
2                                                  Stray   
3                                     Grand Theft Auto V   
4                                            MultiVersus   
...                                                  ...   
77806                          Rising Islands - Art Book   
77807                                        Atrius Star   
77808  Jigsaw Puzzle Pack - Pixel Puzzles Ultimate: T...   
77809  Jigsaw Puzzle Pack - Pixel Puzzles Ultimate: M...   
77810                       Mervils: A VR Adventure Demo   

                                                    tags  
0      FPS, Shooter, Multiplayer, Competitive, Action...  
1      Free to Play, Multiplayer, Battle Royale, Shoo...  
2      Cats, Adventure, Cyberpunk, Cute, Atmospheric,...  
3      Open World, Action, Multiplayer, Automobile Si...  
4      Multiplayer, Co-op, 2D Fighter, Action, Compet...  
...                                                  ...  
77806                                   Adventure, Indie  
77807  Action, Roguelite, Roguelike, Artificial Intel...  
77808  Indie, Casual, Simulation, Strategy, Action, S...  
77809  Indie, Casual, Simulation, Sports, Strategy, F...  
77810  Adventure, RPG, VR, Platformer, Puzzle, Puzzle...  

[77811 rows x 2 columns]

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [39]:
from nltk import SnowballStemmer, PorterStemmer, LancasterStemmer
from nltk.stem import WordNetLemmatizer
import nltk

In [72]:
# nltk.download('wordnet')
lemmatizer = WordNetLemmatizer()

def Lemming_tokenizer(str_input):
    words = str_input.lower().split(',')
    words = [lemmatizer.lemmatize(word.strip()) for word in words]
    return words

In [73]:
vectorizer = TfidfVectorizer(tokenizer=Lemming_tokenizer)

In [74]:
# vectorizer?

In [75]:
X = vectorizer.fit_transform(test.tags)

In [76]:
X

<300x345 sparse matrix of type '<class 'numpy.float64'>'
	with 5886 stored elements in Compressed Sparse Row format>

In [77]:
some = vectorizer.get_feature_names()

In [78]:
some

['"1990s"',
 '"beat em up"',
 '"shoot em up"',
 '1980s',
 '2.5d',
 '2d',
 '2d fighter',
 '2d platformer',
 '3d',
 '3d fighter',
 '3d platformer',
 '3d vision',
 '4 player local',
 '4x',
 '6dof',
 'action',
 'action roguelike',
 'action rpg',
 'action rts',
 'action-adventure',
 'addictive',
 'adventure',
 'agriculture',
 'alien',
 'alternate history',
 'america',
 'animation & modeling',
 'anime',
 'arcade',
 'archery',
 'artificial intelligence',
 'assassin',
 'atmospheric',
 'atv',
 'auto battler',
 'automation',
 'automobile sim',
 'base building',
 'basketball',
 'battle royale',
 'beautiful',
 'blood',
 'board game',
 'building',
 'bullet hell',
 'capitalism',
 'card battler',
 'card game',
 'cartoon',
 'cartoony',
 'casual',
 'cat',
 'character action game',
 'character customization',
 'choices matter',
 'choose your own adventure',
 'cinematic',
 'city builder',
 'class-based',
 'classic',
 'co-op',
 'co-op campaign',
 'cold war',
 'colony sim',
 'colorful',
 'combat',
 'comedy

In [79]:
X

<300x345 sparse matrix of type '<class 'numpy.float64'>'
	with 5886 stored elements in Compressed Sparse Row format>

In [80]:
from sklearn.cluster import KMeans

In [83]:
kmeans = KMeans(random_state=1,n_clusters=5,verbose=1)

In [84]:
kmeans.fit_predict(X)

Initialization complete
Iteration 0, inertia 453.86240609524737
Iteration 1, inertia 241.0132818899333
Iteration 2, inertia 236.24677754172203
Iteration 3, inertia 235.2640939981282
Iteration 4, inertia 235.01903687448714
Iteration 5, inertia 234.88829738120324
Iteration 6, inertia 234.8600269910237
Converged at iteration 6: strict convergence.
Initialization complete
Iteration 0, inertia 439.46119535703366
Iteration 1, inertia 243.32423975897566
Iteration 2, inertia 239.98011060843558
Iteration 3, inertia 237.575386370864
Iteration 4, inertia 235.5756551106844
Iteration 5, inertia 234.09867683627715
Iteration 6, inertia 233.7884426106333
Iteration 7, inertia 233.71829845803424
Iteration 8, inertia 233.69899417875453
Converged at iteration 8: strict convergence.
Initialization complete
Iteration 0, inertia 430.6221708830452
Iteration 1, inertia 240.60245673683607
Iteration 2, inertia 236.88795062564168
Iteration 3, inertia 235.87934624835026
Iteration 4, inertia 235.60502937396473
Iter

array([1, 1, 0, 4, 0, 1, 2, 1, 1, 0, 1, 2, 2, 0, 2, 1, 1, 1, 1, 4, 0, 1,
       1, 0, 2, 0, 4, 1, 0, 2, 4, 2, 3, 0, 1, 0, 4, 0, 3, 1, 0, 0, 1, 1,
       4, 2, 4, 0, 4, 4, 3, 2, 2, 1, 0, 0, 4, 4, 0, 2, 1, 1, 0, 1, 1, 0,
       2, 1, 4, 0, 3, 1, 0, 4, 2, 4, 3, 3, 4, 0, 0, 0, 1, 0, 2, 4, 1, 1,
       0, 1, 3, 3, 1, 0, 2, 2, 4, 0, 1, 2, 0, 1, 3, 1, 1, 4, 1, 0, 2, 0,
       1, 4, 4, 1, 3, 4, 0, 1, 1, 2, 1, 4, 3, 0, 0, 0, 4, 0, 1, 1, 0, 4,
       1, 0, 1, 4, 1, 4, 1, 0, 0, 0, 2, 3, 0, 0, 3, 0, 2, 3, 1, 1, 4, 1,
       4, 3, 1, 0, 4, 1, 0, 1, 0, 0, 0, 4, 0, 0, 0, 2, 2, 4, 1, 0, 3, 4,
       1, 4, 4, 0, 1, 3, 0, 0, 4, 0, 0, 0, 0, 1, 0, 2, 1, 0, 0, 4, 1, 1,
       1, 0, 1, 0, 4, 0, 4, 3, 0, 3, 3, 1, 0, 1, 3, 1, 0, 3, 2, 0, 0, 2,
       0, 0, 0, 0, 3, 0, 2, 3, 0, 1, 0, 3, 4, 1, 0, 1, 1, 0, 3, 0, 0, 4,
       1, 1, 1, 0, 0, 3, 1, 3, 4, 0, 0, 2, 0, 0, 0, 0, 3, 2, 3, 2, 0, 0,
       0, 4, 2, 0, 0, 0, 1, 2, 0, 0, 3, 3, 0, 3, 4, 1, 0, 0, 4, 4, 1, 2,
       0, 0, 3, 1, 1, 4, 4, 3, 3, 3, 0, 0, 0, 0])

In [87]:
df['title'].head(10)

0    Counter-Strike: Global Offensive
1                       Apex Legends™
2                               Stray
3                  Grand Theft Auto V
4                         MultiVersus
5               Red Dead Redemption 2
6                                Rust
7                 PUBG: BATTLEGROUNDS
8                           Destiny 2
9                 MONSTER HUNTER RISE
Name: title, dtype: object